language: php

php:
    - 7.1

before_script:
    - composer install

script:
    - bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then php bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi
